pluginManagement {
    repositories {
        maven {
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        maven {
            name = "Mojang"
            url = "https://libraries.minecraft.net/"
        }

        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/"
        }

        mavenCentral()
    }
}

rootProject.name = "tibia-chat-tabs"